### ISSUE TITLE
what do the params `pixel_means` and `pixel_stds` mean?

### ISSUE THREAD

**Issue by wulikai1993** [StanislasBertrand/RetinaFace-tf2#5]
and why operating the image tensor as following, in `RetinaFace.detect()`:
```bash
for i in range(3):
        im_tensor[0, i, :, :] = (img[:, :, 2 - i] / pixel_scale - pixel_means[2 - i]) / pixel_stds[
            2 - i]
net_out = self.model.predict(im_tensor.transpose(0, 2, 3, 1))
```

**Comment by StanislasBertrand** [comment]
I understand why this is unclear. 

In reality this step does 3 things :
- switch from BGR to RGB (i -> 2-i)
- add a dimension to fit he input shape of the neural network
- subtract scale and divide by standard deviation of the training dataset. In our case, scale is 0 and std is 1, so this step actually makes no difference. I left it there as a habit

I will try to divide this step into 3 distinct steps so it is clearer in the coming days. Or feel free to make a PR for this :)
