### ISSUE TITLE
What should I compile？

### ISSUE THREAD

**Issue by zhjikoshlizhzc** [StanislasBertrand/RetinaFace-tf2#9]
I don't understand the third step in the installation process: 'Then build the RCNN Module by running: make'

What should I compile.

**Comment by StanislasBertrand** [comment]
There is a Makefile in the project, so if you run the make command from the root of the directory, it will run the instructions in the Makefile. These instructions compile the module in the rcnn/ directory which is used for non maximum suppression (nms)
